services:
  hp-project:
    image: maven:3.8.8-eclipse-temurin-17
    volumes:
      - ./:/app
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "8090:8080"

    networks:
      - hp-test
    environment:
      - TZ=Asia/Shanghai

networks:
  hp-test:
    driver: bridge