version: '3.8'
services:
  lingtron-backend-test:
    image: maven:3.8.8-eclipse-temurin-17
    volumes:
      - ./:/app
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "8090:8080"
    extra_hosts:
      - "lingtron.host:host-gateway"
    networks:
      - lingtron-test
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env


networks:
  lingtron-test:
    driver: bridge