services:
  hp-project:
    image: maven:3.8.8-jdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "8090:8080"
    environment:
      - TZ=Asia/Shanghai