services:
  hp-project:
    image: maven:3.8.8-eclipse-temurin-17
    volumes:
      - ./:/app
      - /root/.m2:/root/.m2  # 挂载Maven仓库缓存
    working_dir: /app
    command: mvn clean spring-boot:run
    ports:
      - "8090:8080"
    environment:
      - TZ=Asia/Shanghai
      - MAVEN_OPTS=-Dmaven.repo.local=/root/.m2/repository -Duser.home=/root
    networks:
      - hp-test
  
networks:
  hp-test:
    driver: bridge  # 使用默认的 bridge 网络驱动


